### ISSUE TITLE
Missing Dockerfiles?

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/GSS#3]
Hi,
Docker images are available on https://hub.docker.com/r/moovida/gss, but I see no Dockerfile here. Could you please share it?

**Comment by AndrewM-** [comment]
Same issue, I think.  I cannot install GSS in docker on either Win 10 or on Ubuntu 20.04 as the manifest is missing.

**Comment by moovida** [comment]
Ahhhh, you are right.

Things are as following. The last version (which I should have released already, but is currently being tested by a highschool for survey class, so I figured it would be a good stress-test, will no longer be dockerized.

Actually it will be a simple script to run it. And it will have some fixes inside, so I would suggest to go after that.

I can dig out the previous dockerfile, if there is still interest.

Anyways, I will try to release this week.

**Comment by frafra** [comment]
I would be happy to work on Docker support for GSS.

Having a single container for both the software and the database is not a good practice, so I would like to create a new Dockerfile just for GSS, with a Docker compose file to help running both GSS and Postgres.

**Comment by moovida** [comment]
Hu @frafra , I am afraid all I have left of the old docker file is this:
```

############################################################
# Dockerfile to create a GSS test image
############################################################

FROM moovida/postgis_java8:pg12_j8
MAINTAINER Andrea Antonello (www.hydrologis.com)

EXPOSE 8080 443 5432

RUN mkdir -p /home/gssworkspace

COPY gss /home/

WORKDIR /home

#CMD ["java", "-Xmx1g", "-jar", "gss-backbone-0.1.0.jar", "/home/gssworkspace/", "testPwd", "jdbc:postgresql://localhost:5432/test"]
```

So everything was bundled inside a folder and then executed. 

But then I stopped using it, since I now find it simpler to run a bash script.

But, if you are interested, we could work on a dockerfile for the app together. It won't be very different from the above, since the same method applies (copy the installation folder and execute it).
No, actually what changes is that we are now on java 14, so the java 8 docker image it was taking from will no longer work.

**Comment by moovida** [comment]
this can be closed I guess
