### ISSUE TITLE
GSS Server - Microsoft Edge - OSMap tiles not rendered

### ISSUE THREAD

**Issue by mbalaatgit** [geopaparazzi/GSS#34]
Hi,

Greetings.

GSS rewrite is a great back end for Smash applications. Has many features that are very impressive and work very well. Thanks for the effort.

Would like to record an observation here.

When I use MS:Edge browser, the openstreetmap tiles are not rendered due to CORS issue. With Firefox, immediately post install it has the same issue. But the issue disappears (map rendered) (in firefox), when I click on the attributes table icon.

Is there something that I could do to mitigate this issue in MS:Edge?

Also observed that the photos orientation is different from that of what I see in Smash app. (rotated 270 degrees. ) in the server.

Bala.

**Comment by moovida** [comment]
Hi @mbalaatgit , this is actualy something we have no power over. The osm servers block accesses to their server when too much usage is done. So OSM is there as an example, but the idea is that GSS users configure different TMS or WMS in the admin for the different projects.

Regarding teh pictures, yes, that is a known issue, which is why we have a rotate button. The right way would be to properly read the exif tags, but that is not on teh roadmap right now, I am afraid.

**Comment by mbalaatgit** [comment]
Hi @moovida,

Thanks for the response. 

The MS:edge issue , I thought it was due to the CORS issue ar the GSS Server end. Let me try the TMS options, as an alternative.

Regarding the pictures, is there a rotate button inthe forms view option?

![image](https://github.com/geopaparazzi/GSS/assets/83762273/a97bfb00-3fbc-4909-b4f7-57b6fa2c3c18)

**Comment by moovida** [comment]
In fact, you have to click on the picture to see it large and there you can rotate it if necessary.

**Comment by mbalaatgit** [comment]
Hi Moovida,

Thanks. I can see the picture with original alignment, when I double click. This is good enough. However, I could not locate any button to rotate! I am closing this with this comment. 

Thanks again for the hard work and a greate piece of software!!
